version: '3.8'

services:
  web:
    build: .
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn university_management.main:app --host 0.0.0.0'
    volumes:
      - .:/university_management
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=postgresql://admin:admin@db:5432/university_management_db
    depends_on:
      - db
      - adminer

  db:
    image: postgres:15.3-bullseye
    restart: always
    ports:
      - 5432
    env_file:
      - config/.env
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/1_init_schema.sql
      - ./dump_data.sql:/docker-entrypoint-initdb.d/2_init_data.sql
      - ./test_queries.sql:/test_queries.sql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
