version: '3.8'

services:
  web:
    build: .
    command: uvicorn university_management.main:app --host 0.0.0.0
    volumes:
      - .:/university_management
    ports:
      - 8000:8000

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - .:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
