CREATE TABLE "classrooms" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" timestamp DEFAULT (current_timestamp),
  "class_number" integer NOT NULL,
  "building" varchar NOT NULL
);

CREATE TABLE "courses" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" timestamp DEFAULT (current_timestamp),
  "name" varchar NOT NULL,
  "teacher" varchar,
  "student" varchar,
  "grade" integer,
  "classroom" integer
);

CREATE TABLE "curriculums" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" timestamp DEFAULT (current_timestamp),
  "name" varchar UNIQUE NOT NULL,
  "courses" integer,
  "semester" integer,
  "course_duration" integer
);

CREATE TABLE "departments" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar UNIQUE NOT NULL,
  "facult" varchar,
  "created_at" timestamp DEFAULT (current_timestamp)
);

CREATE TABLE "exams" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "course" integer,
  "classroom" integer,
  "student" varchar,
  "grade" integer,
  "exam_datetime" timestamp DEFAULT (current_timestamp),
  "created_at" timestamp DEFAULT (current_timestamp)
);

CREATE TABLE "faculties" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar UNIQUE NOT NULL,
  "created_at" timestamp DEFAULT (current_timestamp)
);

CREATE TABLE "grades" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "grade" integer UNIQUE NOT NULL,
  "created_at" timestamp DEFAULT (current_timestamp)
);

CREATE TABLE "groups" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar UNIQUE NOT NULL,
  "department" varchar,
  "created_at" timestamp DEFAULT (current_timestamp)
);

CREATE TABLE "independent_tasks" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "independent_task" varchar UNIQUE NOT NULL,
  "student" varchar,
  "grade" integer,
  "created_at" timestamp DEFAULT (current_timestamp)
);

CREATE TABLE "schedules" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "schedule" varchar UNIQUE NOT NULL,
  "semester" integer,
  "exam" integer,
  "course" integer,
  "group_name" varchar,
  "classroom" integer,
  "created_at" timestamp DEFAULT (current_timestamp)
);

CREATE TABLE "semesters" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "semester" integer UNIQUE NOT NULL,
  "academic_yaer" varchar,
  "created_at" timestamp DEFAULT (current_timestamp)
);

CREATE TABLE "students" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "full_name" varchar UNIQUE NOT NULL,
  "group_name" varchar,
  "created_at" timestamp DEFAULT (current_timestamp)
);

CREATE TABLE "buildings" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "address" varchar UNIQUE NOT NULL,
  "created_at" timestamp DEFAULT (current_timestamp)
);

CREATE TABLE "teachers" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "full_name" varchar UNIQUE NOT NULL,
  "created_at" timestamp DEFAULT (current_timestamp)
);

CREATE TABLE "training_programs" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar UNIQUE NOT NULL,
  "course" integer,
  "independent_tasks" integer UNIQUE,
  "exam" integer,
  "created_at" timestamp DEFAULT (current_timestamp)
);

ALTER TABLE "classrooms" ADD FOREIGN KEY ("building") REFERENCES "buildings" ("address") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "courses" ADD FOREIGN KEY ("teacher") REFERENCES "teachers" ("full_name") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "courses" ADD FOREIGN KEY ("student") REFERENCES "students" ("full_name") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "courses" ADD FOREIGN KEY ("grade") REFERENCES "grades" ("grade") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "curriculums" ADD FOREIGN KEY ("courses") REFERENCES "courses" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "curriculums" ADD FOREIGN KEY ("semester") REFERENCES "semesters" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "departments" ADD FOREIGN KEY ("facult") REFERENCES "faculties" ("name") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "exams" ADD FOREIGN KEY ("course") REFERENCES "courses" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "exams" ADD FOREIGN KEY ("classroom") REFERENCES "classrooms" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "exams" ADD FOREIGN KEY ("student") REFERENCES "students" ("full_name") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "exams" ADD FOREIGN KEY ("grade") REFERENCES "grades" ("grade") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "groups" ADD FOREIGN KEY ("department") REFERENCES "departments" ("name") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "independent_tasks" ADD FOREIGN KEY ("student") REFERENCES "students" ("full_name") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "independent_tasks" ADD FOREIGN KEY ("grade") REFERENCES "grades" ("grade") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "schedules" ADD FOREIGN KEY ("semester") REFERENCES "semesters" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "schedules" ADD FOREIGN KEY ("exam") REFERENCES "exams" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "schedules" ADD FOREIGN KEY ("course") REFERENCES "courses" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "schedules" ADD FOREIGN KEY ("group_name") REFERENCES "groups" ("name") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "schedules" ADD FOREIGN KEY ("classroom") REFERENCES "classrooms" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "students" ADD FOREIGN KEY ("group_name") REFERENCES "groups" ("name") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "training_programs" ADD FOREIGN KEY ("course") REFERENCES "courses" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "training_programs" ADD FOREIGN KEY ("independent_tasks") REFERENCES "independent_tasks" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "training_programs" ADD FOREIGN KEY ("exam") REFERENCES "exams" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "courses" ADD FOREIGN KEY ("classroom") REFERENCES "classrooms" ("id") ON DELETE CASCADE ON UPDATE CASCADE;